### ISSUE TITLE
Hand Only Frankmocap

### ISSUE THREAD

**Issue by AhmedShalabe** [carlosedubarreto/b3d_mocap_import#12]
Is the addon capable of only converting PKL files exported from hand-only mocaps from frank mocap or it's for full-body mocap?

**Comment by carlosedubarreto** [comment]
At the moment no. Only body mocap for frankmocap

**Comment by AhmedShalabe** [comment]
Do you think it's possible to convert hand-only PKL files to full body PKL files, resulting in an armature with only hand movements?

**Comment by carlosedubarreto** [comment]
I think it can be possible, but I think it would be easier to import only the hands to a separated model. a hands only model.

**Comment by AhmedShalabe** [comment]
Thanks very much for your effort :)
Hope you are able to achieve this soon 
Thanks again for your effort :)
