### ISSUE TITLE
SMPL-X import

### ISSUE THREAD

**Issue by leilaUEA** [carlosedubarreto/b3d_mocap_import#13]
Hi, Thank you for very useful content, I had a question about importing smplx models using the addon mentioned here:
https://www.youtube.com/watch?v=-vvSjAyiK_g

I tried to import the result of smplify-x to blender using the addon but encounter an error
https://github.com/vchoutas/smplify-x

I was wondering is there any way to import the smplx models? 
Thank you very much in advance!
I look forward to hearing from you

Best regards,
Leila

**Comment by carlosedubarreto** [comment]
It was my mistake, when I did the video I though the github page would be the one to donwload.

But to get the addon to do as it is done in the video, you have to download from this page

https://smpl-x.is.tue.mpg.de/downloads (at the end of the page where its written "SMPL-X Blender Add-on")
![image](https://user-images.githubusercontent.com/4061130/121820642-63544980-cc6a-11eb-8ac9-a7239c3def73.png)


After getting this addon, you install it in blender and the video will make sense 😊

**Comment by leilaUEA** [comment]
Thanks very much for your response, Sorry I think I didn't explain my question well, the video shows exporting an fbx file, but I was asking about another capability of the add-on which is the "load pose" button (mentioned in the description:
+ Load pose from .pkl file (full pose with 55 joints in Rodrigues notation))

So the Github repository (https://github.com/vchoutas/smplify-x) can fit a smplx model to a picture and outputs a .pkl file, that should be read by the "load pose" option of the blender add-on, but when I tried, it was unsuccessful and giving error...

**Comment by carlosedubarreto** [comment]
Oh sorry, I totally misinterpreted your question.
But I think I cant help you with that, as I dont know how to use it.
This problem seems to be from the SMPL-X Addon (if I understood correctly this time 😊). 
I just used it to export the male FBX to use in mocap_import.

**Comment by leilaUEA** [comment]
Yes, you are right, the problem is from the add-on.
Thanks very much I appreciate the works and guidance you shared.
Best Regards,
Leila

**Comment by carlosedubarreto** [comment]
Sorry for not being able to help you on that.
If you have further issue, I'll se if I can help you on the next one. 😊
