### ISSUE TITLE
How to install Mocap_PE_data_import for Blender?

### ISSUE THREAD

**Issue by jamalknight** [carlosedubarreto/b3d_mocap_import#19]
Hi Carlos

Is there a link to the steps to install the Blender mocap importer called Mocap_PE_data_import?
I would like to open the output of EasyMocap in Blender.

The files I have are: `_init_ helper load_mocap` and `test_panel` but I am unsure where these files need to go for Blender or how to install.

Regards,
Jamal

**Comment by jamalknight** [comment]
Preferences - addons - install zip file
+ enable.

**Comment by carlosedubarreto** [comment]
You are right...
I never remember to to put instructions on how to install it 😅
