### ISSUE TITLE
Some problems with installing MOCAP PE Data Import

### ISSUE THREAD

**Issue by zhanghongyong123456** [carlosedubarreto/b3d_mocap_import#21]
Blender version 2.93 is installed in Windows, and the installation of Mocap_PE_data_import_ALPHA is completed. When loading data, this error occurs. Should I modify the source code of Blender
![50](https://user-images.githubusercontent.com/48466610/124383647-22e36b00-dd00-11eb-8059-d156bd2ec18a.png)

**Comment by zhanghongyong123456** [comment]
When I downloaded the 2.92 version of Blender to install the MOCAP PE Data_import, I got the following two screens
![51](https://user-images.githubusercontent.com/48466610/124383873-4b1f9980-dd01-11eb-812b-00ca8353182b.png)
![52](https://user-images.githubusercontent.com/48466610/124383875-4eb32080-dd01-11eb-9157-b1cb2191343d.png)
There's no interface like your video tutorial，like this
![53](https://user-images.githubusercontent.com/48466610/124383889-668aa480-dd01-11eb-8fe7-b877538da83b.png)
https://www.youtube.com/watch?v=8gGua4xek90&list=PLYzax7LPWaADMqDjc9rnAOC3tsd35zZGL&index=1

**Comment by carlosedubarreto** [comment]
> Blender version 2.93 is installed in Windows, and the installation of Mocap_PE_data_import_ALPHA is completed. When loading data, this error occurs. Should I modify the source code of Blender
> ![50](https://user-images.githubusercontent.com/48466610/124383647-22e36b00-dd00-11eb-8059-d156bd2ec18a.png)

Try to use version Beta 0.722
So much passed that I don even remember who that is working.

**Comment by carlosedubarreto** [comment]
> When I downloaded the 2.92 version of Blender to install the MOCAP PE Data_import, I got the following two screens
> ![51](https://user-images.githubusercontent.com/48466610/124383873-4b1f9980-dd01-11eb-812b-00ca8353182b.png)
> ![52](https://user-images.githubusercontent.com/48466610/124383875-4eb32080-dd01-11eb-9157-b1cb2191343d.png)
> There's no interface like your video tutorial，like this
> ![53](https://user-images.githubusercontent.com/48466610/124383889-668aa480-dd01-11eb-8fe7-b877538da83b.png)
> https://www.youtube.com/watch?v=8gGua4xek90&list=PLYzax7LPWaADMqDjc9rnAOC3tsd35zZGL&index=1

Try on more thing.
Uninstall this version you have in blender 2.92

Close blender, open it again.
Install beta 0.722.

If the problem persists, please record a video showing the process you are doing.
Because I have no idea what is happening with your installation.

**Comment by zhanghongyong123456** [comment]
> > Blender version 2.93 is installed in Windows, and the installation of Mocap_PE_data_import_ALPHA is completed. When loading data, this error occurs. Should I modify the source code of Blender
> > ![50](https://user-images.githubusercontent.com/48466610/124383647-22e36b00-dd00-11eb-8059-d156bd2ec18a.png)
> 
> Try to use version Beta 0.722
> So much passed that I don even remember who that is working.

I installed Beta 0.73 in Blender 2.93 and still have the same error

**Comment by zhanghongyong123456** [comment]
> > When I downloaded the 2.92 version of Blender to install the MOCAP PE Data_import, I got the following two screens
> > ![51](https://user-images.githubusercontent.com/48466610/124383873-4b1f9980-dd01-11eb-812b-00ca8353182b.png)
> > ![52](https://user-images.githubusercontent.com/48466610/124383875-4eb32080-dd01-11eb-9157-b1cb2191343d.png)
> > There's no interface like your video tutorial，like this
> > ![53](https://user-images.githubusercontent.com/48466610/124383889-668aa480-dd01-11eb-8fe7-b877538da83b.png)
> > https://www.youtube.com/watch?v=8gGua4xek90&list=PLYzax7LPWaADMqDjc9rnAOC3tsd35zZGL&index=1
> 
> Try on more thing.
> Uninstall this version you have in blender 2.92
> 
> Close blender, open it again.
> Install beta 0.722.
> 
> If the problem persists, please record a video showing the process you are doing.
> Because I have no idea what is happening with your installation.

I installed Beta 0.73 version in Blender 2.92 version and it works normally. Thank you for your timely reply and answer.I think it's some compatibility issues  with version Blender 2.93

**Comment by carlosedubarreto** [comment]
can you send the file you are trying to import for me to test it?
