### ISSUE TITLE
Error when import pkl file in blender

### ISSUE THREAD

**Issue by eragondr** [carlosedubarreto/b3d_mocap_import#22]
so iam using blender 2.93 and addon 0.7222
when iam using sk import Frankmocap 
![image](https://user-images.githubusercontent.com/28474355/124390670-df482b80-dd16-11eb-8fad-96419e2188cb.png)
then hit import 
![image](https://user-images.githubusercontent.com/28474355/124390694-f6871900-dd16-11eb-8c3a-0b2718bde3b7.png)
and i got this error
![image](https://user-images.githubusercontent.com/28474355/124390716-0c94d980-dd17-11eb-839f-b83cff406dde.png)

the cmd line code  i use for frankmocap is : "python -m demo.demo_bodymocap --input_path 1.mp4 --out_dir ./mocap_output --save_pred_pkl"
the pkl file can be find in the zip 
[1.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6760129/1.zip)

**Comment by carlosedubarreto** [comment]
you file is different.
I'm creating another button to import it.
Maybe in an hour it might be ready.


I'll replay when I finish it.

**Comment by eragondr** [comment]
> Your file is different.
> I'm creating another button to import it.
> Maybe in an hour it might be ready.
> 
> I'll reply when I finish it.

Have you re check with frankmocap . Demo_bodymocap because it is weird if we use the same repo(frankmocap repo) but have different output

**Comment by carlosedubarreto** [comment]
> > Your file is different.
> > I'm creating another button to import it.
> > Maybe in an hour it might be ready.
> > I'll reply when I finish it.
> 
> Have you re check with frankmocap . Demo_bodymocap because it is weird if we use the same repo(frankmocap repo) but have different output

I created another import method from the file youve sent.
Its possible that people from frankmocap changed the output file.

You can donwload the update from 

https://carlosedubarreto.gumroad.com/l/mocap_import
or 
https://www.patreon.com/posts/53292966

here is the new button
![image](https://user-images.githubusercontent.com/4061130/124392937-6f15b780-dcce-11eb-88b9-dbc98ea235bf.png)


I took the time and fixed the orientation.
When we import it load tilted, now it load upside down. Its not perfect, but it was worst.

**Comment by eragondr** [comment]
Thank you for all your works. Iam really appreciate your help. Your scrip works but seem to be the motion is still mess up compare with the the smpl model showing in the preview when iam using cmd line code. is there any way i can improve the motion for my fbx file.
God bless you

**Comment by carlosedubarreto** [comment]
You can try different size for SK Multi
![image](https://user-images.githubusercontent.com/4061130/124481581-ce330500-dd7e-11eb-9e27-f68bb3fdb10c.png)

usually a number between 1 and 2 works better.

I noticed your data was odd. but I thought it was just a test 😅

**Comment by eragondr** [comment]
The proplem is the 3model seem to be Sliding on the floor. You can see in the video when i put left leg up the right leg should be stay still but it is  Sliding on the floor. :))) is there any way to fix this or apply the inverse kinematics for the model. 
You the best sir 🥇 

https://user-images.githubusercontent.com/28474355/124485221-8d66da80-ddd6-11eb-813a-10f2e030d143.mp4

**Comment by carlosedubarreto** [comment]
Wow this is the result imported in Maya?????
Its better than I expected....

Well about the feet sliding there are some method you can try, but I know how to do it only inside blender.

can you send me the fbx or the bvh so I can try here when I got some time left?
I'll record and show you.

**Comment by eragondr** [comment]
> Wow this is the result imported in Maya?????
> Its better than I expected....
> 
> Well about the feet sliding there are some method you can try, but I know how to do it only inside blender.
> 
> can you send me the fbx or the bvh so I can try here when I got some time left?
> I'll record and show you.

well i have edit the FBX file a little when i import it in Maya. it would be great if you and i work together to import the rig which have controller to make the motion more perfect, you are the master in python code , and i have experience in 3d rig and animation.
By the way have you got any idea about the sliding , think the problem is about the hip, thing is the the result render in frankmocap kind good but when you export to fbx, it is not so great. you can find the result  in zip file
[rendered.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6765140/rendered.zip)

**Comment by eragondr** [comment]
The fbx filehttps://drive.google.com/file/d/1YYzkc1LWhdn76kMCyTc-9LowxsY7M6gh/view?usp=sharing

**Comment by carlosedubarreto** [comment]
I made a recording trying to show what you could do to fix the feet sliding 
https://youtu.be/TcSi4zpS4pA

And the result file you can grab at
https://disk.yandex.ru/d/oaNxao1sN8AZeQ

Sorry I had to record it fast because of the lack of time, and everybody here is sleeping, so the whispering voice 😊

**Comment by eragondr** [comment]
:)))) thank you for your help. Actually i can do it manually , but the thing is the animation is only in only 51 frames and the time it take to edit one the longer than the one that i animate manually by hand. So basically this project is unusable in real life. Iam loking for a way to get animation from the video that help reduce the time animate manually by hand. :))) 
Can i improve anything in the python code ?

**Comment by carlosedubarreto** [comment]
I see your point.
And that was exactly my thought at the beggning...

But after months diggin on the mocap matter, I see that its very unlikely that I can have a incredible solution that I wont have to do manual tweak.

The best one I saw to get "mocap" data is easymocap, and it is difficult to set it up to use, and even though, its not perfect (but is the best one I've seen.


Another solution that I'm enjoying a lot is mediapipe.
At the moment I'm doing some tests to make better mediapipe import (the one that mocap_import addon has, is not good)


So maybe you can have  better mocap data using one of them. (easymocap or the new mediapipe import I'm workling on)

**Comment by eragondr** [comment]
Love your effort. Iam on the reseach to. Iam looking for some 3d pose estimation. But open pose seem to be to old. So i ran into this repo  https://github.com/facebookresearch/VideoPose3D

You can check and leave a rely for me.

Just found it yesterday. Iam trying to get the pose postion and rotation for it

**Comment by carlosedubarreto** [comment]
Thanks for the link.
Probably I wont be able to  test it anytime soon, But I starred it to make easier to find it again.

**Comment by eragondr** [comment]
Thanks for your support , if you need anything just feed free to contact me one email : thagsau@gmail.com.
