### ISSUE TITLE
Importing EasyMocap finger motion

### ISSUE THREAD

**Issue by Mario-LuX** [carlosedubarreto/b3d_mocap_import#23]
Today I try to import SMPL-X model into Blender 2.93.1 using EasyMoCap, I tried easymocap and successufully get the SMPL-full folder which contains a lot of json files, BTW I previously successfully import SMPL model into blender and I did this because I want to do the retargeting as the video https://www.youtube.com/watch?v=gvqGxQsPHuc&list=PLYzax7LPWaAAkTEXSWZanCsDmuZ8y3Bq7&index=4

But I got this error with Blender
FBX Import: start importing E:\3DProject\SMPL Series\smplx\SMPLX-Male.fbx
FBX version: 7400
        FBX import: Prepare...
                Done (0.000000 sec)

        FBX import: Templates...
                Done (0.000000 sec)

        FBX import: Nodes...
                Done (0.015625 sec)

        FBX import: Connections...
                Done (0.000000 sec)

        FBX import: Meshes...
                Done (0.187500 sec)

        FBX import: Materials & Textures...
                Done (0.000000 sec)

        FBX import: Cameras & Lamps...
                Done (0.000000 sec)

        FBX import: Objects & Armatures...
                Done (0.046875 sec)

        FBX import: ShapeKeys...
                Done (5.265625 sec)

        FBX import: Animations...
                Done (0.000000 sec)

        FBX import: Assign materials...
                Done (0.000000 sec)

        FBX import: Assign textures...
                Done (0.000000 sec)

        FBX import: Cycles z-offset workaround...
                Done (0.000000 sec)

        Done (5.859375 sec)

Import finished.
success load
Python: Traceback (most recent call last):
  File "C:\Users\adminis\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\b3d_mocap_import-main\load_mocap.py", line 344, in execute
    bpy.data.shape_keys["Key"].key_blocks[k].slider_min = -10
KeyError: 'bpy_prop_collection[key]: key "Basis" not found'

location: <unknown location>:-1

I'll appreciate it if someone can help me.

**Comment by Mario-LuX** [comment]
And here is my json files generated in SMPL-full folder.
[smpl_full.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6838883/smpl_full.zip)

**Comment by carlosedubarreto** [comment]
From What I saw, it could be a problem with the fbx SMPL-X model
Did you make it work?

**Comment by Mario-LuX** [comment]
@carlosedubarreto Thanks, it works later. So I close this issue. I don't know sometime blender will have problems when I import other things or conduct other experiments before.
