### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by JelleRouquart** [carlosedubarreto/b3d_mocap_import#26]
![error](https://user-images.githubusercontent.com/56624980/133458269-57cba41c-be7e-4914-9d6f-f631d6227d0f.PNG)

This happens when I click on Animation  MOCAP Import

**Comment by carlosedubarreto** [comment]
Please try this instructions.

https://www.patreon.com/posts/script-to-opencv-54890147

I think it only works with the portable version of blender. (the zip file)

**Comment by JelleRouquart** [comment]
Hey Carlos, I tried but it didn't work. Can you explain 'the portable version of blender' I found one but it just opened blender.

**Comment by carlosedubarreto** [comment]
Sure. Its this one
https://www.blender.org/download/Blender2.93/blender-2.93.4-windows-x64.zip/

in the site you find it here (or download via the link i posted above
![image](https://user-images.githubusercontent.com/4061130/133573161-5993006d-d834-4278-a095-48aa8b6af306.png)

**Comment by JelleRouquart** [comment]
Thankyou for the quick reply, I really appriciate it :)


But it still doesn't work...

1. So I installed the Portable version of Blender

2. Then I Installed the code in the scripting array of Blender:
`import subprocess
import sys
import os
path to python.exe
python_exe = os.path.join(sys.prefix, 'bin', 'python.exe')
py_lib = os.path.join(sys.prefix, 'lib', 'site-packages','pip')
...........`

3. Then I tried to install the cv2 and Mediapipe:
`import cv2
import mediapipe`

4. But i still got the error:
`Traceback (most recent call last): File "<blender_console>, line 1, in <module> ModuleNotFoundError: No module named 'mediapipe''`

**Comment by JelleRouquart** [comment]
![Capture](https://user-images.githubusercontent.com/56624980/133585596-282ae1d2-90e7-4d10-b48c-8ea02eba5fe3.PNG)
![Capture02](https://user-images.githubusercontent.com/56624980/133585600-10575e5f-adb0-4f19-bd17-74b4db39ed8d.PNG)

**Comment by carlosedubarreto** [comment]
it would be this console
![image](https://user-images.githubusercontent.com/4061130/133587021-d027928c-3f16-45a4-bfd9-b5b7c796a900.png)

**Comment by JelleRouquart** [comment]
![Capture3](https://user-images.githubusercontent.com/56624980/133587484-cd392fe3-961b-4281-b95e-1168006f59e3.PNG)

ow sorry here it is

**Comment by JelleRouquart** [comment]
should I do the command?

**Comment by carlosedubarreto** [comment]
From what you showed, looks like it is the problem I was expecting.
The installation went to the system installation of python


Let me try on this... wait a moment please.

**Comment by carlosedubarreto** [comment]
can you go to cmd and run
`set pythonpath`
and show what shows up?

**Comment by JelleRouquart** [comment]
Just in command Prompt from windows? not in Blender?
I am just new in blender sorry ;) (come from C4D)
![Capture04](https://user-images.githubusercontent.com/56624980/133589145-4faa60d1-def7-4662-b8c8-6f3df9d3800d.PNG)

**Comment by carlosedubarreto** [comment]
Yeah it was from windows. you did it correctly...
let me try one more thing, just a moment again.

I wanted to test if we could make it work more easily.
There is another solution but its not so user friendly

**Comment by carlosedubarreto** [comment]
I tried to make something easier but Iwont be able to give more time on it today... sorry.

But I have another issue explaining a way that was able to work
can you try this solution?

https://github.com/carlosedubarreto/vibe_win_install/issues/17#issuecomment-899016167

**Comment by JelleRouquart** [comment]
alright, thanks a lot for the help!! I will try it :)

**Comment by JelleRouquart** [comment]
It worked! I copied and pasted the files and is was allright! Thanks for the help! made my day 💯

**Comment by carlosedubarreto** [comment]
Thanks a lot for the feedback.,
Have fun 😊
