### ISSUE TITLE
Can't import as NLA Strip from OMNIVERSE

### ISSUE THREAD

**Issue by pitanello** [carlosedubarreto/b3d_mocap_import#32]
Hello
I am using blender 3 (i tried also with 2.93), after i exported the model trough the addon and i made all the set up in omniverse, i exported as maya cache the result. If i import the model with the modifier everything works well but id i try to import as NLA Strip i get this result, do you know why?
Thanks
![mocapImportasNLAStrip](https://user-images.githubusercontent.com/11668850/153405562-3a88a75e-faad-42c4-8282-2c7c434f8c6f.jpg)

PS the models are from Human Generator Addon

**Comment by carlosedubarreto** [comment]
interessant, I would have to test to see what is the problem.
But, have you tried using the full body?
You should use only the head.

**Comment by pitanello** [comment]
My bad Carlos, yes i was using the full body than i found your other tutorial on how to transfer the NLA Strip and worked perfectly.
Do you have any paypal donation account? If i am going to use your tool in production i will definitly pay for it.
Thanks

**Comment by carlosedubarreto** [comment]
Thanks for the offer. I dont have paypal donation account, but if you like to pay something, you could check my gumroad.
Most of things are free or paid with discount code (due size limitation on free products) 

But anyway, if you´d like to pay, you can do on this same addon in my gumroad.
https://carlosedubarreto.gumroad.com/l/mocap_import

And thanks a lot for the interest and feedback.
