### ISSUE TITLE
error while using your tool 

### ISSUE THREAD

**Issue by mujtaba-hike** [carlosedubarreto/b3d_mocap_import#36]
Hi, I am trying to import the easymocap output into blender using ur tool but i am getting an error. I tried using blender 3 and 2.8 on mac

<img width="814" alt="Screenshot 2022-11-10 at 9 55 30 AM" src="https://user-images.githubusercontent.com/56671032/201002803-ef08fd8d-1224-48ec-b2c1-18f0968879d4.png">

**Comment by carlosedubarreto** [comment]
I didn't test on MAC but theoricaly it should work.
Usually the problem with importing easymocap is hving the correct SMPL file to import.
Please double check it.

**Comment by mujtaba-hike** [comment]
I have checked it. It's the male fbx for maya.

**Comment by mujtaba-hike** [comment]
I also tried on windows 11 with blender 2.9. There is no error but the model has no animation. it only stands in T pose

**Comment by mujtaba-hike** [comment]
can u tell which blender version and os u have tried on?

**Comment by mujtaba-hike** [comment]
also, plz check on the latest easymocap output

**Comment by carlosedubarreto** [comment]
if you are using the version to get the fingers, you will need SMPLX, to have that file, you need to get the blender addon from smplx, export the model in FBX to use in the addon.

There is a long time that I dont work with those parts of the addon.

If you want to crete your own stuff with easymocap, I would suggest to use the blender version of easymocap I did a while ago.
There you can find more detailed information (video tutorial) showing the process, I gues it will be much better to follow.

https://carlosedubarreto.gumroad.com/l/ceb_easymocap_multicam

and if you want some fast and easy to use way to create mocap, but not as good as the mulkticamera easymocap version, I made another version using the monocular solution.

https://carlosedubarreto.gumroad.com/l/ceb_em_monocular

Both addons can be downloaded for free, there is a coup0on on the description of both.

**Comment by mujtaba-hike** [comment]
I am not using the fingers.. i am using smpl model in easymocap to generate the animation from an input video. i am attaching the output here.
[dance_moves.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/9978585/dance_moves.zip)

**Comment by carlosedubarreto** [comment]
I think you used the monocular one, right?
I've tested here and I could only load the data you've sent after checking the monocular button, then I had this result
![image](https://user-images.githubusercontent.com/4061130/201042375-4f9593c3-7e65-4d2d-b120-2dc21cded713.png)

Its not a beautiful result, but at least is moving :)

so, what you probably missed was the monocular import
![image](https://user-images.githubusercontent.com/4061130/201042501-7229241a-0484-48e8-9210-ed08219c14f7.png)


and use it with version 2.9x, there is a problem with blender 3.x versions
