### ISSUE TITLE
ModuleNotFoundError: cv2 when generating mocap in Blender 2.91

### ISSUE THREAD

**Issue by Eydec** [carlosedubarreto/b3d_mocap_import#5]
cv2 and mediapipe aren't installed in Blender (checked through blender python console), despite mediapipe appearing in pip list -u in console.

Environment: Windows 10

Error message follows

location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:***\***\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Mocap_PE_data_import\load_mocap.py", line 1404, in execute
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by carlosedubarreto** [comment]
Please try this code. on the script screen

```
import subprocess
import sys
import os
 
# path to python.exe
python_exe = os.path.join(sys.prefix, 'bin', 'python.exe')
 
# upgrade pip
subprocess.call([python_exe, "-m", "ensurepip"])
subprocess.call([python_exe, "-m", "pip", "install", "--upgrade", "pip"])
 
# install required packages
subprocess.call([python_exe, "-m", "pip", "install", "opencv-python"])

```

and click run like this :
![image](https://user-images.githubusercontent.com/4061130/113579745-182f1200-95fb-11eb-8308-1a06b530f631.png)

**Comment by Eydec** [comment]
Created a new script, c+p the code you posted, and ran.
After it finished, I tried importing video via mediapipe and got the same error.

**Comment by carlosedubarreto** [comment]
can you run again the code I provided and place here the result that shows on the console? (it must show the instalation log)

**Comment by Eydec** [comment]
Nothing in the python console,

bpy.ops.text.run_script()
In the Info console

**Comment by carlosedubarreto** [comment]
Oh sorry, I mean this console
![image](https://user-images.githubusercontent.com/4061130/113583655-4e22c500-9600-11eb-836f-e24a8a49bd8b.png)

then something like this will show
![image](https://user-images.githubusercontent.com/4061130/113583684-5a0e8700-9600-11eb-9754-792b964346b9.png)


Then you run the code again e post here the result, please

**Comment by Eydec** [comment]
＿＿＿
Looking in links: c:\Users\\AppData\Local\Temp\tmp_09novfa
Requirement already satisfied: setuptools in c:\users\\appdata\roaming\python\python37\site-packages (39.0.1)
Requirement already satisfied: pip in c:\users\\appdata\roaming\python\python37\site-packages (21.0.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\\appdata\roaming\python\python37\site-packages (21.0.1)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opencv-python in c:\users\\appdata\roaming\python\python37\site-packages (4.5.1.48)
Requirement already satisfied: numpy>=1.14.5 in c:\program files\blender foundation\blender 2.91\2.91\python\lib\site-packages (from opencv-python) (1.17.5)
＿＿＿

**Comment by carlosedubarreto** [comment]
looks like it installed the opencv on your default windows python instalation.

Do this.
on windows explorer, go to this address
c:\users\appdata\roaming\python\python37\site-packages
![image](https://user-images.githubusercontent.com/4061130/113586432-e1a9c500-9603-11eb-84c9-2b30bad8942e.png)

copy the folder "cv2"

and past it here
c:\program files\blender foundation\blender 2.91\2.91\python\lib\site-packages

![image](https://user-images.githubusercontent.com/4061130/113586641-1fa6e900-9604-11eb-9c30-61d6fd46135c.png)

**Comment by Eydec** [comment]
Tried Generate mocap, got the following error:
＿＿＿
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\Mocap_PE_data_import\load_mocap.py", line 1405, in execute
    import mediapipe as mp
ModuleNotFoundError: No module named 'mediapipe'
＿＿＿

**Comment by carlosedubarreto** [comment]
Now click on this button on blender, and show put here what show in the console
![image](https://user-images.githubusercontent.com/4061130/113594547-3c481e80-960e-11eb-9b3c-64a0a3e3cf02.png)
