### ISSUE TITLE
os.sep instead of '\\' for portability in path string construction

### ISSUE THREAD

**Issue by k30n1** [carlosedubarreto/b3d_mocap_import#8]
Minor portability bug: In order to make the plugin work in Blender on Linux, I had to replace backslash filename separators with os.sep, which should resolve to backslash in Windows and forward slash in other OSes. This was limited to the load_mocap.py module, just replace `'\\'` with `os.sep` in 4 places.  

Thanks for all the work you've put into this add-on!

**Comment by carlosedubarreto** [comment]
Wow, thanks for the help on the linux fix.
I'll keep the issu open while the file is not fixed and tested.

**Comment by carlosedubarreto** [comment]
Update done, thanks a lot @k30n1
